# docker-compose.yml
version: '3'
services:
  serving:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: serving
      args:
        PORT: ${SERVING_PORT}
    image: 'ift6758/serving:${VERSION}'
    ports:
      - '${SERVING_PORT}:${SERVING_PORT}'
    environment:
      COMET_API_KEY: '${COMET_API_KEY}'
    container_name: 'serving'
  streamlit:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: streamlit
      args:
        PORT: ${STREAMLIT_PORT}
    image: 'ift6758/streamlit:${VERSION}'
    ports:
      - '${STREAMLIT_PORT}:${STREAMLIT_PORT}'
    environment:
      STREAMLIT_ENV: '${STREAMLIT_ENV}'
    container_name: 'streamlit'



